export enum RouteAPI {
    Login = '/login',
    Register = '/register',
    Dashboard = '/dashboard',
    CreateProfile = '/create-profile',
    EditProfile = '/edit-profile',
    AddExperience = '/add-experience',
    AddEducation = '/add-education',
    Profiles = '/profiles',
    Profile = '/profile/',
    Posts = '/posts',
    Pages = '/pages',
    About = '/pages/about',
    Service = '/pages/service',
    ContactUs = '/pages/contact-us',
    ToDo = '/pages/to-do',
}
